### ISSUE TITLE
Not finding locast2plex in Plex DVR

### ISSUE THREAD

**Issue by TruckinFool** [tgorgdotcom/locast2plex#168]
Good morning,

I am trying to get Locast2Plex to work and am encountering the following errors.  Can you take a look and see what might be the problem?

I'm running Windows 10 Build 19041, Python 3.9, Plex Media Server 1.21.0.3711 and the latest release of Locast2plex.

I have attached screenshots of the error in Plex and the python code.

Thanks for the help!
Larry 

![dvr1](https://user-images.githubusercontent.com/67014170/103094676-f5389f00-45c3-11eb-824c-013a337ab80f.PNG)

**Comment by CTJohnK** [comment]
Try clicking the "...Enter its network address manually" link, then put in the L2P ip and port, something like - 192.168.1.50:6077.  Use the L2P ip and the port you configured if you changed it.

**Comment by TruckinFool** [comment]
I get the same result entering the IP and port manually. Plex is on port 32400 and I have changed the port in the config file.

**Comment by CTJohnK** [comment]
Plex is port 32400, L2P is usually 6077 unless you changed it.

**Comment by TruckinFool** [comment]
127.0.0.1 and yes I added the port line to the config file with 32400 specified. Keeping it at 6077 did nothing, not even an error.

**Comment by SJLBoulder** [comment]
Hi, TruckinFool.  plex_accessible_port in the config file is to change your locast2plex port.  There is no need to specify that option if you want locast2plex to be accessible to plex on port 6077 (the default).  In PLEX, in addition to specifying the IP address of locast2plex, I found that I needed to also include the port.  So in PLEX when configuring the tuner address, I specified both the ip address and port of locast2plex:  192.168.1.11:6700

**Comment by sschadwick** [comment]
I'm running into the same issue when I run the latest Docker container of locast2plex. Here's the relevant error message that I see, looks like there's a missing argument on `lib/tuner_interface.py:222`.

```
File "/app/lib/tuner_interface.py", line 222, in do_POST
self.do_response(200, 'text/html')
TypeError: do_response() missing 1 required positional argument: 'reply_str'
```

@TruckinFool: Your second image includes your plex token, this is sensitive information and you should assume that it's been compromised.

**Comment by CTJohnK** [comment]
@TruckinFool, if you are running Plex and L2P on the same box, the Plex port is 32400.  When you open your browser to access Plex, this is the port in the URL link.  L2P uses port 6077. This is the port Plex will use to communicate with L2P.

You do not want to set the L2P port to 32400 as it will conflict with Plex.

Could you paste the contents of your config.ini - removing your username and password from the paste for security - into this thread?

**Comment by sschadwick** [comment]
Reverting to the 0.5.3 docker image resolved the issue.

**Comment by TruckinFool** [comment]
> @TruckinFool, if you are running Plex and L2P on the same box, the Plex port is 32400. When you open your browser to access Plex, this is the port in the URL link. L2P uses port 6077. This is the port Plex will use to communicate with L2P.
> 
> You do not want to set the L2P port to 32400 as it will conflict with Plex.
> 
> Could you paste the contents of your config.ini - removing your username and password from the paste for security - into this thread?
> 
> Your config.ini should look something like -
> 
> plex_accessible_ip=192.168.1.5 (or whatever ip address your window pc has)
> plex_accessible_port=6077
> 
> The ip could also be set to 127.0.0.1 which is the 'loopback' but only useful if Plex and L2P are on the same box.
> 
> If your config.ini file does not have the port entry, that is fine as it means you will use the default 6077.
> 
> Taking the settings from my sample above, when you get to the Plex DVR setup screen, you would select to manually enter the ip information and type in either 192.168.1.5:6077 or 127.0.0.1:6077.

Here is a copy of my config.ini file right now.  So if I understand correctly, removing the port line and letting it default to 6077 should resolve the issue?  L2P and Plex are on the same machine/plex server, so I should be able to keep using the default 127.0.0.1 also?

[main]
plex_accessible_ip = 127.0.0.1
locast_username = xxxxx
locast_password = xxxx
uuid = zmshzlvh
plex_accessible_port = 32400

**Comment by TruckinFool** [comment]
> @TruckinFool, if you are running Plex and L2P on the same box, the Plex port is 32400. When you open your browser to access Plex, this is the port in the URL link. L2P uses port 6077. This is the port Plex will use to communicate with L2P.
> 
> You do not want to set the L2P port to 32400 as it will conflict with Plex.
> 
> Could you paste the contents of your config.ini - removing your username and password from the paste for security - into this thread?
> 
> Your config.ini should look something like -
> 
> plex_accessible_ip=192.168.1.5 (or whatever ip address your window pc has)
> plex_accessible_port=6077
> 
> The ip could also be set to 127.0.0.1 which is the 'loopback' but only useful if Plex and L2P are on the same box.
> 
> If your config.ini file does not have the port entry, that is fine as it means you will use the default 6077.
> 
> Taking the settings from my sample above, when you get to the Plex DVR setup screen, you would select to manually enter the ip information and type in either 192.168.1.5:6077 or 127.0.0.1:6077.

Doing as you suggested worked and I have Plex DVR setup and working with L2P.  Thanks for the help!  Have a great new year guys.

**Comment by CTJohnK** [comment]
Yes, removing the port line will default L2P to 6077, or just change it from 32400 to 6077, your choice.As for the ip address, yes 127.0.0.1 would work since Plex and L2P are on the same box; personally I like to explicitly put in the ip address as I use static ip addresses for my hardwired equipment.On Dec 26, 2020 5:41 PM, TruckinFool <notifications@github.com> wrote:

@TruckinFool, if you are running Plex and L2P on the same box, the Plex port is 32400. When you open your browser to access Plex, this is the port in the URL link. L2P uses port 6077. This is the port Plex will use to communicate with L2P.
You do not want to set the L2P port to 32400 as it will conflict with Plex.
Could you paste the contents of your config.ini - removing your username and password from the paste for security - into this thread?
Your config.ini should look something like -
plex_accessible_ip=192.168.1.5 (or whatever ip address your window pc has)
plex_accessible_port=6077
The ip could also be set to 127.0.0.1 which is the 'loopback' but only useful if Plex and L2P are on the same box.
If your config.ini file does not have the port entry, that is fine as it means you will use the default 6077.
Taking the settings from my sample above, when you get to the Plex DVR setup screen, you would select to manually enter the ip information and type in either 192.168.1.5:6077 or 127.0.0.1:6077.

Here is a copy of my config.ini file right now.  So if I understand correctly, removing the port line and letting it default to 6077 should resolve the issue?  L2P and Plex are on the same machine/plex server, so I should be able to keep using the default 127.0.0.1 also?
[main]
plex_accessible_ip = 127.0.0.1
locast_username = xxxxx
locast_password = xxxx
uuid = zmshzlvh
plex_accessible_port = 32400

**Comment by gewgaw4u** [comment]
@sschadwick Have you ever been able to upgrade past 0.5.3?

**Comment by TruckinFool** [comment]
No, I have not tried. It's working fine and don't want to chance messing it up, lol.

**Comment by sschadwick** [comment]
Haven’t tried, 0.5.3 is stable for me.
