### ISSUE TITLE
Geo Location Error

### ISSUE THREAD

**Issue by Nomar383** [tgorgdotcom/locast2plex#22]
Getting this error when logging inL
```
Getting user location...
Error during geo IP acquisition: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
Exiting...
```

Any ideas?

**Comment by java007md** [comment]
Seeing the same error message here. Using the command line interface on linux, installed on the same server that is running plex, and using the local network address for the 'addy' parameter.

**Comment by RonRN18** [comment]
I too have run into the same issue. I am NOT using this in a Docker, nor on the same machine as Plex, but as an Ubuntu 20.04.1 Server VM on a Xen Server. When I run the command, I get:

 `Locast2Plex v0.4.2
DEBUG MODE ACTIVE
UUID found.
UUID set to: uxzxztsr...
Logging into Locast using username ************@******.com...
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 1602966145
Getting user location...
Error during geo IP acquisition: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
Exiting...
`

**Comment by Nomar383** [comment]
I’m using the docker image under Ubuntu Server on the same VM as Plex. I
would happily switch to the command line install if that fixes the issue.

Maybe it would be possible to add a env variable to manually set the
location? Not like it’s going to change much anyway

**Comment by java007md** [comment]
Looking at the Locast site, it appears that the area we are in is experiencing issues - that may be the root of the issue, at least for me. Will test again when Locast resolves the local issues.

**Comment by tgorgdotcom** [comment]
Hmmm, this looks more like an error coming from the Geo IP service I'm using to determine location.  I just tested it now and seems okay, maybe it was an issue on their end?  Could you try again and let me know?  Thanks!

**Comment by Nomar383** [comment]
Still getting the same error

**Comment by java007md** [comment]
Also still getting the same error. Locast.org site shows the local issues for our area area cleared up.

**Comment by RonRN18** [comment]
I too get the same results.

**Comment by java007md** [comment]
Visiting https://get.geojs.io/ from a chrome browser gives me: NET::ERR_CERT_AUTHORITY_INVALID

`get.geojs.io normally uses encryption to protect your information. When Google Chrome tried to connect to get.geojs.io this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be get.geojs.io, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit get.geojs.io right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.`

Visiting from Firefox provides results:

`IP: xxx.xxx.xxx.xxx
Country: United States (US)
City: Maryland
Timezone: America/New_York
Org: UUNET (AS701)

---
Docs and more on our website https://geojs.io/`

**Comment by RonRN18** [comment]
I have just tried it now and it is now working. I did absolutely nothing different but it worked.

**Comment by Nomar383** [comment]
Still the same error for me. Hasn't worked at any point so far unfortunately

**Comment by java007md** [comment]
I was able to get this to work yesterday by hard coding the mock location settings. Added to both Plex and the Jellyfin and was working fine. Tried again just now, with the same command line that worked yesterday, and received a different error (user validation related). Will post that in a separate issue report.

**Comment by borFSU** [comment]
I don't know how many of you are using pihole or something similiar for ad/domain blocking, but whitelisting the get.geojs.io fixed this issue for me.

**Comment by RedGreen007** [comment]
I whitelisted it, but i still can't get it to list my location. 

I feel like the geolocation service is down. I have done this a couple times now and sometimes it grabs it and then stops and other times it just doesn't find it.

**Comment by Nomar383** [comment]
I just ended up hardcoding the location and it works fine now. Maybe just add an option for that as a startup switch or something?

**Comment by RedGreen007** [comment]
For me it hangs up at starting SSDP server and never goes past this point.

**Comment by tgorgdotcom** [comment]
@RedGreen007 That was my bad, I forgot to print a message saying locast2plex was fully loaded (fixed in 0.5.2).  If you get to that point in 0.4.2, it is running normally.

For everyone else who is having trouble with location, I do have an "undocumented" feature in 0.5.2 where you can specify latitude/longitude in our new config,ini file (I'm keeping it somewhat quiet because I don't want people using it to access channels outside of their service area).   Note that there are some extra steps to upgrade to 0.5.2, so make sure you re-read `README.md`.  To specify latitude/longitude, add the following lines to the end of config.ini:

```
override_latitude=xxxxx
override_longitude=xxxxx
```

You can get your latitude/longitude using Google Maps.

**Comment by Nomar383** [comment]
I pulled the latest version and switched to using the new config file. The lat/long config options work great for me! Thanks!

**Comment by tgorgdotcom** [comment]
@RedGreen007 are you still running into any issues?

**Comment by myrison** [comment]
> I don't know how many of you are using pihole or something similiar for ad/domain blocking, but whitelisting the get.geojs.io fixed this issue for me.

Thanks for this tip, this fixed my issue as well.

I would definitely recommend referencing this answer in the troubleshooting page, which is [currently blank for this issue](https://github.com/tgorgdotcom/locast2plex/wiki/Troubleshooting-and-Common-Issues#errno-99-address-not-available).

**Comment by Nomar383** [comment]
For me, I'm not sure that was the issue. I was able to navigate to the
geojs.io page manually from a browser, even before I whitelisted it. After
whitelisting the site, it still didn't work for me. The manual location
settings worked perfectly as a workaround

**Comment by myrison** [comment]
Fair enough, when @tgorgdotcom has time, it'll be helpful for future users to see both of the solutions in this thread in the FAQ which should save time down the road for new users.

**Comment by tgorgdotcom** [comment]
Ah yeah, it was in the FAQ, but it was placed in a section above it, perhaps incorrectly labeled.  Fixed it now.
