### ISSUE TITLE
Consider increasing the value for the 'analyzeduration' and 'probesize' options

### ISSUE THREAD

**Issue by cpare** [tgorgdotcom/locast2plex#268]
When attempting to view some channels I am getting the error below, resulting in no audio stream.

Are either of the parameters suggested configurable through the config.ini?

```
127.0.0.1 - - [22/Jul/2021 12:53:13] "GET /lineup_status.json HTTP/1.1" 200 -
Getting station info for 1611180505391...
Determining best video stream for 1611180505391...
Found 0 Playlists
No variant streams found for this station.  Assuming single stream only.
127.0.0.1 - - [22/Jul/2021 12:53:16] "GET /watch/1611180505391 HTTP/1.1" 200 -
[hls @ 0x5573a523f780] Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels, fltp): unspecified sample rate
Consider increasing the value for the 'analyzeduration' and 'probesize' options
127.0.0.1 - - [22/Jul/2021 12:53:21] "GET /discover.json HTTP/1.1" 200 -

```

**Comment by ecowitness** [comment]
the message that starts "[hls" is from ffmpeg, which locast2plex uses internally

these are not locast2plex options

what operating system and ffmpeg are you using?

**Comment by rocky4546** [comment]
Agree with @ecowitness that we would need the OS and version of ffmpeg.  Also, if you gave the DMA city, we could check to see if anyone else has an issue with that channel.  It may be the codecs you have loaded on your system are causing the issue.

**Comment by cpare** [comment]
Thanks for the follow-up, here are my details...

I am on Ubuntu 20.04.2 LTS 
```
cpare@Appserver:~$ uname -a
Linux Appserver 5.8.0-63-generic #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Hardware:**
```
Memory: 23.4 GiB
Processor: AMD® Fx(tm)-8310 eight-core processor × 8 
Graphics: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti]
Disk Capacity: 8.4 TB
```

**ffmpeg info**
```
cpare@Appserver:~$ ffmpeg -version

ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100</pre>
```

**Python**
```
cpare@Appserver:~/locast2plex-main$ python3 --version

Python 3.8.10
```

**Location from the app (Specifically this is when trying to tune CometTV (Don't judge me)**
```
Got location as Orlando - DMA 534 - Lat\Lon 28.605276\-81.52123
```

**Comment by ecowitness** [comment]
We are doing all the simple things to start diagnosis. I don't understand the message you are getting.

So...can you issue "ffmpeg -codecs" and and look for lines like these
```

 DEA.L. aac                  AAC (Advanced Audio Coding) (decoders: aac aac_fixed )
 D.A.L. aac_latm             AAC LATM (Advanced Audio Coding LATM syntax)
 DEA.L. ac3                  ATSC A/52A (AC-3) (decoders: ac3 ac3_fixed ) (encoders: ac3 ac3_fixed )
```
The list is long, so you don't have to post the whole thing. Just looking to see if ffmpeg can see the codec.

Just to be sure....you are running locast2plex from a command line in a terminal window and not in a docker container.... Do you have more than one ffmpeg on your system? There is an ffmpeg in the l2p github, but I do not use that. I am in a docker container that I built myself.

I'm in a different DMA, so I can't look at that station. I have not had this problem. I don't look at comet very often.

What do get when you use a browser to access this channel from the locast logon screen? Does it play?

The transfer of the tv program is done in lib/tuner_interface. The command is set up to run more or less silently. The codecs are set up as copy. We may get to the point where we need you to modify the python code and change the -loglevel on the ffmpeg invocation.

Is there anything else you want to tell us about that might help? I'm going exhaust my ability to help pretty quickly.

**Comment by rocky4546** [comment]
Thank you for the information.  I am running Ubuntu 20.4.2 LTS on intel hardware.  Running the same version of ffmpeg from ubuntu
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
Python 3.8.10
And I switched to Orlando.
I have a forked version of locast2plex that allows me to change configurations for testing.  I ran with pass-through (bypasses ffmpeg) and for that channel, I did not receive any audio when playing into VLC.  According to VLC, the codec is ADTS stereo streaming at 48K Hz.  If I play channel 6.1 CBS, audio plays fine.  VLC says it has the same audio codec.
This indicates that the issue is possibly with Locast itself.  Now I changed the configuration to play it through ffmpeg.  I did not see your codec error, but it played the audio and not the video. Myself and others have seen this type of issue with Locast when the signal strength is not sufficient.  I have taken channels with these issues and played them directly on the Locast site to find that the issue exists there as well. (audio plays but not video or video plays but not audio.)

There is little that anyone can do when the stream itself has issues.  This seems to happen mostly with 480p streams (which your Comet channel is one.)  You may find that some days are better than others (just like you might see with an antenna.

At least that is my two cents.  Good Luck.

**Comment by ecowitness** [comment]
I bow to this excellent research.

I have opened support tickets with locast and have received excellent support, so I'll share some of that experience.

I always report the problem as seen from my browser and I never mention l2p. 

Of course, this means that the problem must be seen on the locast web page in order to be reported on a ticket, but the issues that I have had with reception (pixelation and audio/video out of sync) have been cleared up very quickly.

**Comment by cpare** [comment]
Thank you both for the very helpful information, at this point I am still running from command-line but look forward to moving to a container in the future.  I will try to replicate the issue from my browser and open a ticket with Locast directly if I can do so.

As an enhancement request it may be nice to investigate if the options ffmpeg suggested allow it a larger sample size to better determine the audio data, improving the success for items like this.

Closing this issue - appreciate the help!
