### ISSUE TITLE
pull access denied   --restart, repository does not exist

### ISSUE THREAD

**Issue by wgstarks** [tgorgdotcom/locast2plex#283]
If I try to run the docker run command with the restart option I get this error-

`wgstarks@mini ~ % docker run -v ~/locast2plex/config.ini:/app/config/config.ini -p 6077:6077 -p 1900:1900/udp tgorg/locast2plex--restart unless-stopped  
Unable to find image 'tgorg/locast2plex--restart:latest' locally
docker: Error response from daemon: pull access denied for tgorg/locast2plex--restart, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.`

**Comment by ecowitness** [comment]
Since nobody else answered.....

There are really two separate issues here, one more important than the other.

The simple one: There is no space after the image name before the --restart, which created an awkward image name that docker couldn't find.

The more important one: after the run, you must specify all options before you specify the name of the image. You have put your restart option in the wrong place; it must appear before the tgorg.

Enjoy.

**Comment by wgstarks** [comment]
Thanks. After a little reading I was fairly sure I had the syntax wrong but hadn't had a chance to test. Glad you confirmed it.

**Comment by wgstarks** [comment]
user error
