### ISSUE TITLE
Docker: Error during login Not Found (with donated account)

### ISSUE THREAD

**Issue by TheCopernicus** [tgorgdotcom/locast2plex#47]
I'm trying to get this docker up and running and I'm running into an issue starting it. It seems like it cannot find my user account, even though I can log into the locast website just fine and I have donated. At first I thought it might be my complex password but I set it to something without crazy special characters and it still does not work. Below is the log, email address has been redacted. Any help is greatly appreciated!

Locast2Plex v0.4.2
DEBUG MODE ACTIVE
UUID found.
UUID set to: zmvhxhmx...
Logging into Locast using username email@domain.com
Error during login: Not Found

Exiting...

**Comment by RedGreen007** [comment]
Make sure your email is verified. Mine was not and caused the same issue. 

[](https://www.locast.org/verify)

**Comment by TheCopernicus** [comment]
Well this is strange. I tried to log into my account and it didn’t let me. Tried a password reset and it said it didn’t exit. And it let me register for a new account with that same email. Even though I have the email from them thanking me for my donation. I’ll have to talk to them to get the donation applied to my “new” account I guess? Haha

Alex Calvin
________________________________

**Comment by tgorgdotcom** [comment]
Hello @TheCopernicus.  Are you still running into any issues?

**Comment by RedGreen007** [comment]
Figured out that docker was looped running an image I thought I deleted. Locked my login attempts. Have not tried again with docker since I got it running executing it with python using nohup. 

Ultimately I think I needed the ability to put in my geolocation because of my pi hole blocking something that I was unable to track. 

I need to try again with docker now that I know why the images never executed properly and was stuck in a login loop to see what happens. 

But I did get it working via python and the config file having geolocation data present. This does however require you to run a command that runs the script in the background so you can close the terminal. (My server runs on a Plex server on Ubuntu 20.04 server running headless)

It will do a slight delay when you first select a channel like it's buffering but it starts up after 5 seconds and plays extremely well from that point on 👍

**Comment by TheCopernicus** [comment]
Nope, I’m good now thanks. Locast support said one of my accounts was @live.com and the other was @live.om. Even though I received both welcome emails to my inbox. But anyway, they deleted the “incorrect” one and I guess that fixed it.

Alex Calvin
________________________________
