### ISSUE TITLE
known_stations Conversation

### ISSUE THREAD

**Issue by deathbybandaid** [tgorgdotcom/locast2plex#95]
I'm not sure I understand what `known_stations.json` is for.

The only issue that even mentions this file is #42 .

My opinion is that Locast gives us channel numbers associated with the content that is hosted BY Locast.
Once we start parsing the EPG into xmltv.xml, I believe manual channel information like this will be out-of-scope for the project.

If users want to make the channel numbers more accurate, we can either have a function built-in for manual channel-mapping, or users can put locast2plex behind xteve to remap the channel numbers.

**Comment by tgorgdotcom** [comment]
Hmmm, to be sure, are you saying the we won't need channel numbers anymore if we move to xmltv.hml?

**Comment by deathbybandaid** [comment]
All that is really important, is xmoth channel numbers match the channels from locast. Since both points of data come from the sam source, it makes channel matching easy.

**Comment by tgorgdotcom** [comment]
Gotcha.  But wouldn't that be confusing for some?  Like if someone who knows that channel 2 usually goes to NBC, but in the xmltv it's in position 1.

**Comment by deathbybandaid** [comment]
We could potentially make a system to allow channel remapping. Alternatively, if locast2plex is behind xteve, that is another way to remap channels.

**Comment by deathbybandaid** [comment]
I also feel like with the number of DMA, this could be an unending whack-a-mole game of submitted issues.

**Comment by tgorgdotcom** [comment]
Just reread this and I think I missed that you mentioned the Locast has channel numbers.  Where does that channel number come from?   I know we can glean a value from callSign, but that doesn't always use the same format for certain markets.

**Comment by deathbybandaid** [comment]
If you look at the api EPG, the numbers are there

**Comment by deathbybandaid** [comment]
Got to a computer, here's example for https://api.locastnet.org/api/watch/epg/501

````

  |  
-- | --
0 |  
id | 104
dma | 501
stationId | "16689"
name | "WCBSDT"
callSign | "2.1 CBS"
logoUrl | "https://static.locastnet.org/logo/NewYork/WCBS.png"
active | true
listings | […]
sequence | 10
logo226Url | "https://static.locastnet.org/roku/NewYork/WCBS.png"
tivoId | 69022174

````

**Comment by FozzieBear** [comment]
DMAs 618 and 725 are good examples of areas that have inconsistent channel number\call sign formatting. 

```
https://api.locastnet.org/api/watch/epg/725

{u'active': True,
 u'callSign': u'KTTW',
 u'dma': 725,
 u'id': 1059,
 ....
 u'logo226Url': u'https://static.locastnet.org/roku/SiouxFalls/KTTW.png',
 u'logoUrl': u'https://static.locastnet.org/logo/SiouxFalls/KTTW.png',
 u'name': u'KTTWDT',
 u'sequence': 10,
 u'stationId': u'35471',
 u'tivoId': 69024841}

https://api.locastnet.org/api/watch/epg/618

{u'active': True,
 u'callSign': u'KPRC',
 u'dma': 618,
 u'id': 339,
 ....
 u'logo226Url': u'https://static.locastnet.org/roku/Houston/KPRC.png',
 u'logoUrl': u'https://static.locastnet.org/logo/Houston/KPRC.png',
 u'name': u'KPRCDT',
 u'sequence': 10,
 u'stationId': u'21250',
 u'tivoId': 69021824}
```

**Comment by tgorgdotcom** [comment]
That's the main reason we have our FCC mapping.  If we can't determine a proper channel number from the returned data,  I do a search by call letters into the tv_stations.json.  

To elaborate, the code first looks at the fcc_dma_markets.json to map DMA market code to the FCC nielsen_dma field in tv_stations.json.  Reason being is we need to filter out stations outside of our DMA when searching, because there could be multiple stations with the same call letters but in completely different locations -- for instance one station is KHGI-TV (the stations we usually think of as a normal CBS/FOX/ABC/NBC channel), and the other is KHGI-LD (a "low power" station).  I'm not sure how well Locast accurately reports whether something is TV or LD, so I don't search for that part of the station string.

So where does known_stations.json come in?  Well, there are times where Locast's reporting callsign is incorrect (call letters may have changed, as the station owners changed, etc. etc.), so we have this data to go by for whenever we don't have good data (either by Locast or by FCC).

It is indeed sort of a monstrosity of a mechanism just to get proper channels, but to the user it's nice not to have to worry about it.

**Comment by deathbybandaid** [comment]
As far as I'm concerned, Locast provides A channel number, and THAT channel number is the same in the EPG data that they provide.

I think people can deal with the channel numbers being incorrect. Otherwise, xteve is really not that difficult to remap channel numbers, along with rewriting the xmltv to match.

Additionally, #92 includes a method for outputting the xmltv. It becomes a convoluted process to remap the channels internally.

**Comment by tgorgdotcom** [comment]
To be sure, I re-tested all of the locations to see how Locast reports channel numbers.  Looks like only Houston and Sioux Falls is returning without channel numbers, which I think is better than it was previously.  If the situation improves further, I'm definitely all for removing the entire FCC check mechanism.  Alternatively, maybe we can skip/remove the FCC checks now, and rely on `known_stations.json` for channel mappings in those areas (at least some of the monstrosity can be removed), with a future hope of removing it entirely.
